# Generated by Django 3.1.7 on 2021-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
